AWSTemplateFormatVersion: 2010-09-09
Description: seconed answer
Parameters:
  KeyName:
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: main
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
    ConstraintDescription: must be a valid EC2 instance type.
  SSHLocation:
    Description:  SSH to the EC2 instances
    Type: String
    Default: 176.44.119.124/32

Resources:
  EC2Instance1
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0bf69afb300c322eb
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: !Ref KeyName
      Tags:
        - Key: key
         Value: key1
        - Key: Type
         Value: Amazon Linux 2
 EC2Instance2:
   Type: 'AWS::EC2::Instance'
   Properties:
     ImageId: ami-0bf69afb300c322eb
     InstanceType: !Ref InstanceType
     SecurityGroups:
       - !Ref InstanceSecurityGroup
     KeyName: !Ref KeyName
     Tags:
       - Key: key
        Value: key
       - Key: Type
        Value: Ubuntu
InstanceSecur

  AZname1:
    Description: The Availability Zone where the Amazon Linux 2 EC2 instance is lunch
    Value: !GetAtt EC2Instance1.AvailabilityZone
  AZname2:
    Description: The Availability Zone where the Ubuntu EC2 instance is launched
    Value: !GetAtt EC2Instance2.AvailabilityZone
  PublicDNS1:
    Description: The public DNS name of the Amazon Linux 2 EC2 instance
    Value: !GetAtt EC2Instance1.PublicDnsName
  PublicDNS2:
    Description: The public DNS name of the Ubuntu EC2 instance
    Value: !GetAtt EC2Instance2.PublicDnsName
  PublicIP1:
    Description: The public IP address of the Amazon Linux 2 EC2 instance
    Value: !GetAtt EC2Instance1.PublicIp
  PublicIP2:
    Description: The public IP address of the Ubuntu EC2 instance
    Value: !GetAtt EC2Instance2.PublicIp
